# Generated by Django 3.2.9 on 2022-07-12 05:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pin', models.CharField(max_length=255)),
                ('codesent', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[(1, 'activate'), (0, 'deactivate')], max_length=20, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('farmer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='farmer/files/')),
                ('createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=10)),
                ('group_type', models.CharField(max_length=20)),
                ('female_farmers', models.IntegerField(default=0)),
                ('male_farmers', models.IntegerField(default=0)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('limit', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(blank=True, choices=[(1, 'activate'), (0, 'deactivate')], max_length=20, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('districtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.district')),
            ],
        ),
        migrations.CreateModel(
            name='Sent_Code_farmerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Sent_Code_farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Recomender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.village')),
            ],
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.recomender'),
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.village'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmergroup'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.recomender'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.village'),
        ),
        migrations.CreateModel(
            name='ExGroupWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('designation', models.CharField(max_length=255)),
                ('telephone_number', models.CharField(max_length=100)),
                ('operation_area', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=9)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.exgroup')),
            ],
        ),
    ]
