# Generated by Django 4.0.3 on 2022-06-13 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_village_createdat_village_updatedat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='farmer/files/')),
                ('createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='villages',
            new_name='village',
        ),
        migrations.RenameField(
            model_name='farmergroup',
            old_name='villages',
            new_name='village',
        ),
        migrations.RenameField(
            model_name='recomender',
            old_name='villages',
            new_name='village',
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='female_farmers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='group_type',
            field=models.CharField(default=datetime.date(2022, 6, 13), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='male_farmers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='pin',
            field=models.CharField(default=datetime.date(2022, 6, 13), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.recomender'),
        ),
    ]
