# Generated by Django 4.0.3 on 2022-06-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_farmergroup_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ex_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExGroupWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('designation', models.CharField(max_length=255)),
                ('telephone_number', models.CharField(max_length=100)),
                ('operation_area', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'ex_group_workers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
