# Generated by Django 4.0.3 on 2022-06-10 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('english', models.CharField(max_length=255)),
                ('arabic', models.CharField(blank=True, max_length=255, null=True)),
                ('lugbara', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('cropid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
                ('livestockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.livestock')),
            ],
        ),
    ]
