# Generated by Django 4.0.3 on 2022-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='arabic_video',
            field=models.FileField(blank=True, null=True, upload_to='arabic_videos/'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='english_video',
            field=models.FileField(blank=True, null=True, upload_to='english_videos/'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='lugba_video',
            field=models.FileField(blank=True, null=True, upload_to='lugba_videos/'),
        ),
    ]
