# Generated by Django 4.0.3 on 2022-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_videoupload_arabic_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed')], default='pending', max_length=10)),
            ],
        ),
    ]
