# Generated by Django 4.0.3 on 2022-06-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_video_arabic_alter_video_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='arabic',
            field=models.FileField(blank=True, null=True, upload_to='videos/arabic/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='english',
            field=models.FileField(blank=True, null=True, upload_to='videos/english/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lugbara',
            field=models.FileField(blank=True, null=True, upload_to='videos/lugbara/'),
        ),
    ]
