# Generated by Django 4.0.3 on 2022-06-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('upload', '0003_alter_video_arabic_alter_video_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='livestockid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.livestock'),
        ),
    ]
