# Generated by Django 4.0.3 on 2022-06-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='repliedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
