# Generated by Django 4.0.3 on 2022-06-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registered',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=10),
        ),
    ]
