# Generated by Django 4.0.3 on 2022-06-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translation',
            new_name='Manual',
        ),
    ]
