# Generated by Django 4.0.3 on 2022-06-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
