# Generated by Django 4.0.3 on 2022-06-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('arabic', models.CharField(max_length=45)),
                ('lugbar', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='crops')),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('arabic', models.CharField(max_length=45)),
                ('lugbar', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='livestock')),
            ],
        ),
    ]
