# Generated by Django 3.2.9 on 2022-07-12 05:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('crop', 'Crop'), ('livestock', 'Livestock')], max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('english', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('arabic', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('lugbara', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('english_audio', models.FileField(blank=True, null=True, upload_to='audio/english/')),
                ('arabic_audio', models.FileField(blank=True, null=True, upload_to='audio/arabic/')),
                ('lugbara_audio', models.FileField(blank=True, null=True, upload_to='audio/lugbara/')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('cropid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
                ('livestockid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.livestock')),
            ],
        ),
    ]
