# Generated by Django 4.0.3 on 2022-06-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
