# Generated by Django 4.0.3 on 2022-06-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_manual_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='arabic_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/arabic/'),
        ),
        migrations.AddField(
            model_name='manual',
            name='english_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/english/'),
        ),
        migrations.AddField(
            model_name='manual',
            name='lugbara_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/lugbara/'),
        ),
    ]
