# Generated by Django 4.0.3 on 2022-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_manual_arabic_audio_manual_english_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='type',
            field=models.CharField(blank=True, choices=[('crop', 'Crop'), ('livestock', 'Livestock')], max_length=255, null=True),
        ),
    ]
