# Generated by Django 4.0.3 on 2022-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.IntegerField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('pin', models.CharField(max_length=255)),
                ('grouptype', models.CharField(blank=True, max_length=255, null=True)),
                ('registrationtype', models.IntegerField(blank=True, null=True)),
                ('femalefarmers', models.CharField(blank=True, max_length=255, null=True)),
                ('malefarmers', models.CharField(blank=True, max_length=255, null=True)),
                ('codesent', models.IntegerField(blank=True, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('farmertype', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.IntegerField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('status', models.IntegerField()),
                ('expiry', models.DateTimeField()),
                ('recommender', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'farmers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'villages',
                'managed': False,
            },
        ),
    ]
