# Generated by Django 4.0.3 on 2022-06-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=45)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.country')),
            ],
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='recommender',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='singlefarmer',
            name='Date_of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlefarmer',
            name='phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='singlefarmer',
            name='recommender',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='singlefarmer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='A', max_length=8),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=45)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.district')),
            ],
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='Village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.village'),
        ),
        migrations.AddField(
            model_name='singlefarmer',
            name='Village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.village'),
        ),
    ]
