# Generated by Django 4.0.3 on 2022-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_country_district_farmergroup_recommender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefarmer',
            name='Date_of_Birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
