# Generated by Django 4.0.3 on 2022-06-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_alter_singlefarmer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefarmer',
            name='Date_of_Birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
