# Generated by Django 4.0.3 on 2022-06-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_farmerfile_rename_villages_farmer_village_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farmer_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
