# Generated by Django 4.0.3 on 2022-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmer_farmer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmergroup',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
