# Generated by Django 4.0.3 on 2022-06-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_exgroups_exgroupworkers_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmergroup',
            name='limit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'active'), (0, 'inactive')], max_length=20, null=True),
        ),
    ]
