# Generated by Django 4.0.3 on 2022-06-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_farmergroup_limit_alter_farmer_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
