# Generated by Django 4.0.3 on 2022-06-17 06:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_delete_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmergroup',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'active'), (0, 'inactive')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Sent_Code_farmerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Sent_Code_farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
        ),
    ]
